/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dandy' at '19.3.16 16:31' with Gradle 2.9
 *
 * @author dandy, @date 19.3.16 16:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
